/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define USART3_IRQ 39

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//Manually pend the pending bit for the USART3 IRQ number in NVIC
	uint32_t *isr1_set_pend = (uint32_t*)(0XE000E204);
	*isr1_set_pend |= (1 << (USART3_IRQ % 32));

	// Enable USART3 IRQ in NVIC
	uint32_t *isr1_en = (uint32_t*)0xE000E104;
	*isr1_en |= (1 << (USART3_IRQ % 32));
}

void USART3_IRQHandler(){
	printf("in USART3 isr\n");
}
