/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Enable all configurable exceptions

	uint32_t *pSHCSR = (uint32_t*) 0xE000ED24;
	*pSHCSR |= (1 << 16); // MEM MANAGE
	*pSHCSR |= (1 << 17); // BUS FAULT
	*pSHCSR |= (1 << 18); // USAGE FAULT

	// Force some undefined instruction
	uint32_t *pSRAM = (uint32_t*) 0x20010000;
	*pSRAM = 0xFFFFFFFF;

	void (*some_address)(void);

	some_address = (void*)0x20010001;

	some_address();

}

// Implement the fault handlers
void HardFault_Handler(void){
	printf("Hard Fault\n");
	while(1);
}
void MemManage_Handler(void){
	printf("Mem manage\n");
	while(1);
}
void BusFault_Handler(void){
	printf("Bus Fault\n");
	while(1);
}
__attribute ((naked))void UsageFault_Handler(void){
	__asm("MRS r0,MSP");
	__asm("B UsageFault_Handler_c");
}

void UsageFault_Handler_c(uint32_t *pBaseStackFrame){
	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("UFSR = %lx\n",(*pUFSR)&0xFFFF);
	printf("MSP = %p\n",pBaseStackFrame);
	printf("R0: %lx",pBaseStackFrame[0]);
	printf("R1: %lx",pBaseStackFrame[1]);
	printf("R2: %lx",pBaseStackFrame[2]);
	printf("R3: %lx",pBaseStackFrame[3]);
	printf("R12: %lx",pBaseStackFrame[4]);
	printf("LR: %lx",pBaseStackFrame[5]);
	printf("PC: %lx",pBaseStackFrame[6]);
	printf("XPSR: %lx",pBaseStackFrame[7]);
	while(1);
}

