/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void){
	__asm("SVC #8");
	uint32_t data;
	__asm volatile("MOV %0,r0":"=r"(data)::);

	printf("New SVC: %ld\n",data);
	for(;;);
}
__attribute ((naked))void SVC_Handler(void){
	__asm("MRS r0,MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pStackBase){
	uint8_t *pMSR_PC = (uint8_t*) pStackBase[6];
	pMSR_PC-=2;
	uint8_t svc_number = *pMSR_PC;
	printf("SVC Number: %d\n",svc_number);
	svc_number+=4;
	pStackBase[0] = svc_number;
}
