/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_AHB1ENR_t volatile *const pClockControlReg = (RCC_AHB1ENR_t*) 0x40023830;
	GPIOx_MODER_t volatile *const pGpioAMode =(GPIOx_MODER_t*) 0x40020000;
	GPIOx_ODR_t volatile *const pGpioOut = (GPIOx_ODR_t*) 0x40020014;

	//ENABLE THE CLOCK FOR GPIOA5
	pClockControlReg->gpioa_en = 1;

	//CONFIGURE GPIOA5 AS OUTPUT
	pGpioAMode->pin_5 = 1;




    while(1){
    	//ENABLE GPIOA5
    	pGpioOut->pin_5 = 1;
    	for(uint32_t i=0;i<5000000;i++);
    	//DISABLE GPIOA5
    	pGpioOut->pin_5 = 0;
    	for(uint32_t i=0;i<5000000;i++);
    }
}
