/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{
	uint32_t *AHB1ENR = (uint32_t*)0x40023830;
	uint32_t *GPIOAMODE = (uint32_t*)0x40020000;
	uint32_t *GPIOAOUTD = (uint32_t*)0x40020014;

	//Enable GPIO Clock for GPIOA
	*AHB1ENR = *AHB1ENR | 0x01;

	//Mask value for clearing = 0xfffff3ff or ~(3 << 10)
	//*GPIOAMODE &= 0xfffff3ff;
	*GPIOAMODE &= ~(3 << 10);

	//Mask value for setting = 0x00000400 or (1 << 10)
	//*GPIOAMODE |= 0x00000400;
	*GPIOAMODE |= (1 << 10);



    /* Loop forever */
	while(1){
		//Toggle the pin
		*GPIOAOUTD ^= (1 << 5);
		for(uint32_t i=0;i<1000000;i++);

	}
}
